// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package checker

import (
	"context"
	"github.com/ONSdigital/dis-web-mount-check/config"
	"github.com/ONSdigital/dis-web-mount-check/deployment"
	"sync"
)

// Ensure, that DeploymentStateGetterMock does implement DeploymentStateGetter.
// If this is not the case, regenerate this file with moq.
var _ DeploymentStateGetter = &DeploymentStateGetterMock{}

// DeploymentStateGetterMock is a mock implementation of DeploymentStateGetter.
//
//	func TestSomethingThatUsesDeploymentStateGetter(t *testing.T) {
//
//		// make and configure a mocked DeploymentStateGetter
//		mockedDeploymentStateGetter := &DeploymentStateGetterMock{
//			DeploymentStateFunc: func(ctx context.Context, jobID string, sequenceCount int) (deployment.DeploymentState, error) {
//				panic("mock out the DeploymentState method")
//			},
//		}
//
//		// use mockedDeploymentStateGetter in code that requires DeploymentStateGetter
//		// and then make assertions.
//
//	}
type DeploymentStateGetterMock struct {
	// DeploymentStateFunc mocks the DeploymentState method.
	DeploymentStateFunc func(ctx context.Context, jobID string, sequenceCount int) (deployment.DeploymentState, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeploymentState holds details about calls to the DeploymentState method.
		DeploymentState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
			// SequenceCount is the sequenceCount argument value.
			SequenceCount int
		}
	}
	lockDeploymentState sync.RWMutex
}

// DeploymentState calls DeploymentStateFunc.
func (mock *DeploymentStateGetterMock) DeploymentState(ctx context.Context, jobID string, sequenceCount int) (deployment.DeploymentState, error) {
	callInfo := struct {
		Ctx           context.Context
		JobID         string
		SequenceCount int
	}{
		Ctx:           ctx,
		JobID:         jobID,
		SequenceCount: sequenceCount,
	}
	mock.lockDeploymentState.Lock()
	mock.calls.DeploymentState = append(mock.calls.DeploymentState, callInfo)
	mock.lockDeploymentState.Unlock()
	if mock.DeploymentStateFunc == nil {
		var (
			deploymentStateOut deployment.DeploymentState
			errOut             error
		)
		return deploymentStateOut, errOut
	}
	return mock.DeploymentStateFunc(ctx, jobID, sequenceCount)
}

// DeploymentStateCalls gets all the calls that were made to DeploymentState.
// Check the length with:
//
//	len(mockedDeploymentStateGetter.DeploymentStateCalls())
func (mock *DeploymentStateGetterMock) DeploymentStateCalls() []struct {
	Ctx           context.Context
	JobID         string
	SequenceCount int
} {
	var calls []struct {
		Ctx           context.Context
		JobID         string
		SequenceCount int
	}
	mock.lockDeploymentState.RLock()
	calls = mock.calls.DeploymentState
	mock.lockDeploymentState.RUnlock()
	return calls
}

// Ensure, that SlackNotifierMock does implement SlackNotifier.
// If this is not the case, regenerate this file with moq.
var _ SlackNotifier = &SlackNotifierMock{}

// SlackNotifierMock is a mock implementation of SlackNotifier.
//
//	func TestSomethingThatUsesSlackNotifier(t *testing.T) {
//
//		// make and configure a mocked SlackNotifier
//		mockedSlackNotifier := &SlackNotifierMock{
//			NotifyFunc: func(ctx context.Context, cfg *config.Config, result string, state bool)  {
//				panic("mock out the Notify method")
//			},
//		}
//
//		// use mockedSlackNotifier in code that requires SlackNotifier
//		// and then make assertions.
//
//	}
type SlackNotifierMock struct {
	// NotifyFunc mocks the Notify method.
	NotifyFunc func(ctx context.Context, cfg *config.Config, result string, state bool)

	// calls tracks calls to the methods.
	calls struct {
		// Notify holds details about calls to the Notify method.
		Notify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg *config.Config
			// Result is the result argument value.
			Result string
			// State is the state argument value.
			State bool
		}
	}
	lockNotify sync.RWMutex
}

// Notify calls NotifyFunc.
func (mock *SlackNotifierMock) Notify(ctx context.Context, cfg *config.Config, result string, state bool) {
	callInfo := struct {
		Ctx    context.Context
		Cfg    *config.Config
		Result string
		State  bool
	}{
		Ctx:    ctx,
		Cfg:    cfg,
		Result: result,
		State:  state,
	}
	mock.lockNotify.Lock()
	mock.calls.Notify = append(mock.calls.Notify, callInfo)
	mock.lockNotify.Unlock()
	if mock.NotifyFunc == nil {
		return
	}
	mock.NotifyFunc(ctx, cfg, result, state)
}

// NotifyCalls gets all the calls that were made to Notify.
// Check the length with:
//
//	len(mockedSlackNotifier.NotifyCalls())
func (mock *SlackNotifierMock) NotifyCalls() []struct {
	Ctx    context.Context
	Cfg    *config.Config
	Result string
	State  bool
} {
	var calls []struct {
		Ctx    context.Context
		Cfg    *config.Config
		Result string
		State  bool
	}
	mock.lockNotify.RLock()
	calls = mock.calls.Notify
	mock.lockNotify.RUnlock()
	return calls
}
