// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package checker

import (
	"context"
	"sync"

	"github.com/ONSdigital/dis-web-mount-check/config"
	"github.com/ONSdigital/dis-web-mount-check/deployment"
)

// SlackNotifierMock is a mock implementation of SlackNotifier.
type SlackNotifierMock struct {
	NotifyFunc func(ctx context.Context, cfg *config.Config, result string, state bool)

	calls struct {
		Notify []struct {
			Ctx    context.Context
			Cfg    *config.Config
			Result string
			State  bool
		}
	}
	lockNotify sync.RWMutex
}

func (m *SlackNotifierMock) Notify(ctx context.Context, cfg *config.Config, result string, state bool) {
	m.lockNotify.Lock()
	defer m.lockNotify.Unlock()
	m.calls.Notify = append(m.calls.Notify, struct {
		Ctx    context.Context
		Cfg    *config.Config
		Result string
		State  bool
	}{ctx, cfg, result, state})
	if m.NotifyFunc != nil {
		m.NotifyFunc(ctx, cfg, result, state)
	}
}

func (m *SlackNotifierMock) NotifyCalls() []struct {
	Ctx    context.Context
	Cfg    *config.Config
	Result string
	State  bool
} {
	m.lockNotify.RLock()
	defer m.lockNotify.RUnlock()
	return append([]struct {
		Ctx    context.Context
		Cfg    *config.Config
		Result string
		State  bool
	}{}, m.calls.Notify...)
}

// DeploymentStateGetterMock is a mock implementation of DeploymentStateGetter.
type DeploymentStateGetterMock struct {
	DeploymentStateFunc func(ctx context.Context, jobID string) (deployment.DeploymentState, error)

	calls struct {
		DeploymentState []struct {
			Ctx   context.Context
			JobID string
		}
	}
	lockDeploymentState sync.RWMutex
}

func (m *DeploymentStateGetterMock) DeploymentState(ctx context.Context, jobID string) (deployment.DeploymentState, error) {
	m.lockDeploymentState.Lock()
	defer m.lockDeploymentState.Unlock()
	m.calls.DeploymentState = append(m.calls.DeploymentState, struct {
		Ctx   context.Context
		JobID string
	}{ctx, jobID})
	if m.DeploymentStateFunc != nil {
		return m.DeploymentStateFunc(ctx, jobID)
	}
	return deployment.DeploymentUnknown, nil
}

func (m *DeploymentStateGetterMock) DeploymentStateCalls() []struct {
	Ctx   context.Context
	JobID string
} {
	m.lockDeploymentState.RLock()
	defer m.lockDeploymentState.RUnlock()
	return append([]struct {
		Ctx   context.Context
		JobID string
	}{}, m.calls.DeploymentState...)
}
